package com.mapuni.gdydcaiji.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mapuni.gdydcaiji.bean.TBuildingInfo;
import com.mapuni.gdydcaiji.bean.TPoiInfo;
import com.mapuni.gdydcaiji.bean.TSocialInfo;
import com.mapuni.gdydcaiji.bean.TVillageInfo;

import com.mapuni.gdydcaiji.database.greendao.TBuildingInfoDao;
import com.mapuni.gdydcaiji.database.greendao.TPoiInfoDao;
import com.mapuni.gdydcaiji.database.greendao.TSocialInfoDao;
import com.mapuni.gdydcaiji.database.greendao.TVillageInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tBuildingInfoDaoConfig;
    private final DaoConfig tPoiInfoDaoConfig;
    private final DaoConfig tSocialInfoDaoConfig;
    private final DaoConfig tVillageInfoDaoConfig;

    private final TBuildingInfoDao tBuildingInfoDao;
    private final TPoiInfoDao tPoiInfoDao;
    private final TSocialInfoDao tSocialInfoDao;
    private final TVillageInfoDao tVillageInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tBuildingInfoDaoConfig = daoConfigMap.get(TBuildingInfoDao.class).clone();
        tBuildingInfoDaoConfig.initIdentityScope(type);

        tPoiInfoDaoConfig = daoConfigMap.get(TPoiInfoDao.class).clone();
        tPoiInfoDaoConfig.initIdentityScope(type);

        tSocialInfoDaoConfig = daoConfigMap.get(TSocialInfoDao.class).clone();
        tSocialInfoDaoConfig.initIdentityScope(type);

        tVillageInfoDaoConfig = daoConfigMap.get(TVillageInfoDao.class).clone();
        tVillageInfoDaoConfig.initIdentityScope(type);

        tBuildingInfoDao = new TBuildingInfoDao(tBuildingInfoDaoConfig, this);
        tPoiInfoDao = new TPoiInfoDao(tPoiInfoDaoConfig, this);
        tSocialInfoDao = new TSocialInfoDao(tSocialInfoDaoConfig, this);
        tVillageInfoDao = new TVillageInfoDao(tVillageInfoDaoConfig, this);

        registerDao(TBuildingInfo.class, tBuildingInfoDao);
        registerDao(TPoiInfo.class, tPoiInfoDao);
        registerDao(TSocialInfo.class, tSocialInfoDao);
        registerDao(TVillageInfo.class, tVillageInfoDao);
    }
    
    public void clear() {
        tBuildingInfoDaoConfig.clearIdentityScope();
        tPoiInfoDaoConfig.clearIdentityScope();
        tSocialInfoDaoConfig.clearIdentityScope();
        tVillageInfoDaoConfig.clearIdentityScope();
    }

    public TBuildingInfoDao getTBuildingInfoDao() {
        return tBuildingInfoDao;
    }

    public TPoiInfoDao getTPoiInfoDao() {
        return tPoiInfoDao;
    }

    public TSocialInfoDao getTSocialInfoDao() {
        return tSocialInfoDao;
    }

    public TVillageInfoDao getTVillageInfoDao() {
        return tVillageInfoDao;
    }

}
