package com.mapuni.gdydcaiji.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mapuni.gdydcaiji.bean.InLine;
import com.mapuni.gdydcaiji.bean.InPoint;
import com.mapuni.gdydcaiji.bean.InSurface;
import com.mapuni.gdydcaiji.bean.TbLine;
import com.mapuni.gdydcaiji.bean.TbPoint;
import com.mapuni.gdydcaiji.bean.TbSurface;

import com.mapuni.gdydcaiji.database.greendao.InLineDao;
import com.mapuni.gdydcaiji.database.greendao.InPointDao;
import com.mapuni.gdydcaiji.database.greendao.InSurfaceDao;
import com.mapuni.gdydcaiji.database.greendao.TbLineDao;
import com.mapuni.gdydcaiji.database.greendao.TbPointDao;
import com.mapuni.gdydcaiji.database.greendao.TbSurfaceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inLineDaoConfig;
    private final DaoConfig inPointDaoConfig;
    private final DaoConfig inSurfaceDaoConfig;
    private final DaoConfig tbLineDaoConfig;
    private final DaoConfig tbPointDaoConfig;
    private final DaoConfig tbSurfaceDaoConfig;

    private final InLineDao inLineDao;
    private final InPointDao inPointDao;
    private final InSurfaceDao inSurfaceDao;
    private final TbLineDao tbLineDao;
    private final TbPointDao tbPointDao;
    private final TbSurfaceDao tbSurfaceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inLineDaoConfig = daoConfigMap.get(InLineDao.class).clone();
        inLineDaoConfig.initIdentityScope(type);

        inPointDaoConfig = daoConfigMap.get(InPointDao.class).clone();
        inPointDaoConfig.initIdentityScope(type);

        inSurfaceDaoConfig = daoConfigMap.get(InSurfaceDao.class).clone();
        inSurfaceDaoConfig.initIdentityScope(type);

        tbLineDaoConfig = daoConfigMap.get(TbLineDao.class).clone();
        tbLineDaoConfig.initIdentityScope(type);

        tbPointDaoConfig = daoConfigMap.get(TbPointDao.class).clone();
        tbPointDaoConfig.initIdentityScope(type);

        tbSurfaceDaoConfig = daoConfigMap.get(TbSurfaceDao.class).clone();
        tbSurfaceDaoConfig.initIdentityScope(type);

        inLineDao = new InLineDao(inLineDaoConfig, this);
        inPointDao = new InPointDao(inPointDaoConfig, this);
        inSurfaceDao = new InSurfaceDao(inSurfaceDaoConfig, this);
        tbLineDao = new TbLineDao(tbLineDaoConfig, this);
        tbPointDao = new TbPointDao(tbPointDaoConfig, this);
        tbSurfaceDao = new TbSurfaceDao(tbSurfaceDaoConfig, this);

        registerDao(InLine.class, inLineDao);
        registerDao(InPoint.class, inPointDao);
        registerDao(InSurface.class, inSurfaceDao);
        registerDao(TbLine.class, tbLineDao);
        registerDao(TbPoint.class, tbPointDao);
        registerDao(TbSurface.class, tbSurfaceDao);
    }
    
    public void clear() {
        inLineDaoConfig.clearIdentityScope();
        inPointDaoConfig.clearIdentityScope();
        inSurfaceDaoConfig.clearIdentityScope();
        tbLineDaoConfig.clearIdentityScope();
        tbPointDaoConfig.clearIdentityScope();
        tbSurfaceDaoConfig.clearIdentityScope();
    }

    public InLineDao getInLineDao() {
        return inLineDao;
    }

    public InPointDao getInPointDao() {
        return inPointDao;
    }

    public InSurfaceDao getInSurfaceDao() {
        return inSurfaceDao;
    }

    public TbLineDao getTbLineDao() {
        return tbLineDao;
    }

    public TbPointDao getTbPointDao() {
        return tbPointDao;
    }

    public TbSurfaceDao getTbSurfaceDao() {
        return tbSurfaceDao;
    }

}
