package com.mapuni.gdydcaiji.database.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mapuni.gdydcaiji.bean.TbLine;
import com.mapuni.gdydcaiji.bean.TbPoint;
import com.mapuni.gdydcaiji.bean.TbSurface;

import com.mapuni.gdydcaiji.database.greendao.TbLineDao;
import com.mapuni.gdydcaiji.database.greendao.TbPointDao;
import com.mapuni.gdydcaiji.database.greendao.TbSurfaceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tbLineDaoConfig;
    private final DaoConfig tbPointDaoConfig;
    private final DaoConfig tbSurfaceDaoConfig;

    private final TbLineDao tbLineDao;
    private final TbPointDao tbPointDao;
    private final TbSurfaceDao tbSurfaceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tbLineDaoConfig = daoConfigMap.get(TbLineDao.class).clone();
        tbLineDaoConfig.initIdentityScope(type);

        tbPointDaoConfig = daoConfigMap.get(TbPointDao.class).clone();
        tbPointDaoConfig.initIdentityScope(type);

        tbSurfaceDaoConfig = daoConfigMap.get(TbSurfaceDao.class).clone();
        tbSurfaceDaoConfig.initIdentityScope(type);

        tbLineDao = new TbLineDao(tbLineDaoConfig, this);
        tbPointDao = new TbPointDao(tbPointDaoConfig, this);
        tbSurfaceDao = new TbSurfaceDao(tbSurfaceDaoConfig, this);

        registerDao(TbLine.class, tbLineDao);
        registerDao(TbPoint.class, tbPointDao);
        registerDao(TbSurface.class, tbSurfaceDao);
    }
    
    public void clear() {
        tbLineDaoConfig.clearIdentityScope();
        tbPointDaoConfig.clearIdentityScope();
        tbSurfaceDaoConfig.clearIdentityScope();
    }

    public TbLineDao getTbLineDao() {
        return tbLineDao;
    }

    public TbPointDao getTbPointDao() {
        return tbPointDao;
    }

    public TbSurfaceDao getTbSurfaceDao() {
        return tbSurfaceDao;
    }

}
