package com.mapuni.gdydcaiji.database.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mapuni.gdydcaiji.bean.TSocialInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TSOCIAL_INFO".
*/
public class TSocialInfoDao extends AbstractDao<TSocialInfo, Long> {

    public static final String TABLENAME = "TSOCIAL_INFO";

    /**
     * Properties of entity TSocialInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Uid = new Property(1, int.class, "uid", false, "UID");
        public final static Property Bm = new Property(2, String.class, "bm", false, "BM");
        public final static Property Csbs = new Property(3, String.class, "csbs", false, "CSBS");
        public final static Property Qxbs = new Property(4, String.class, "qxbs", false, "QXBS");
        public final static Property Xzbs = new Property(5, String.class, "xzbs", false, "XZBS");
        public final static Property Gsjd = new Property(6, String.class, "gsjd", false, "GSJD");
        public final static Property Xqid = new Property(7, String.class, "xqid", false, "XQID");
        public final static Property Name = new Property(8, String.class, "name", false, "NAME");
        public final static Property Firstad = new Property(9, String.class, "firstad", false, "FIRSTAD");
        public final static Property Secondad = new Property(10, String.class, "secondad", false, "SECONDAD");
        public final static Property Thirdad = new Property(11, String.class, "thirdad", false, "THIRDAD");
        public final static Property Forthad = new Property(12, String.class, "forthad", false, "FORTHAD");
        public final static Property Fifad = new Property(13, String.class, "fifad", false, "FIFAD");
        public final static Property Xqdz = new Property(14, String.class, "xqdz", false, "XQDZ");
        public final static Property X = new Property(15, Double.class, "x", false, "X");
        public final static Property Y = new Property(16, Double.class, "y", false, "Y");
        public final static Property Gxsj = new Property(17, java.util.Date.class, "gxsj", false, "GXSJ");
        public final static Property Wyxx = new Property(18, String.class, "wyxx", false, "WYXX");
        public final static Property Lxdh = new Property(19, String.class, "lxdh", false, "LXDH");
        public final static Property Glgx = new Property(20, String.class, "glgx", false, "GLGX");
        public final static Property Xqmj = new Property(21, Double.class, "xqmj", false, "XQMJ");
        public final static Property Optuser = new Property(22, String.class, "optuser", false, "OPTUSER");
        public final static Property Lat = new Property(23, Double.class, "lat", false, "LAT");
        public final static Property Lng = new Property(24, Double.class, "lng", false, "LNG");
        public final static Property Opttime = new Property(25, java.util.Date.class, "opttime", false, "OPTTIME");
        public final static Property Type = new Property(26, String.class, "type", false, "TYPE");
        public final static Property Lysl = new Property(27, String.class, "lysl", false, "LYSL");
        public final static Property Zhs = new Property(28, String.class, "zhs", false, "ZHS");
        public final static Property Lds = new Property(29, String.class, "lds", false, "LDS");
        public final static Property Bj = new Property(30, String.class, "bj", false, "BJ");
        public final static Property Img = new Property(31, String.class, "img", false, "IMG");
        public final static Property Flag = new Property(32, int.class, "flag", false, "FLAG");
    }


    public TSocialInfoDao(DaoConfig config) {
        super(config);
    }
    
    public TSocialInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TSOCIAL_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UID\" INTEGER NOT NULL ," + // 1: uid
                "\"BM\" TEXT," + // 2: bm
                "\"CSBS\" TEXT," + // 3: csbs
                "\"QXBS\" TEXT," + // 4: qxbs
                "\"XZBS\" TEXT," + // 5: xzbs
                "\"GSJD\" TEXT," + // 6: gsjd
                "\"XQID\" TEXT," + // 7: xqid
                "\"NAME\" TEXT," + // 8: name
                "\"FIRSTAD\" TEXT," + // 9: firstad
                "\"SECONDAD\" TEXT," + // 10: secondad
                "\"THIRDAD\" TEXT," + // 11: thirdad
                "\"FORTHAD\" TEXT," + // 12: forthad
                "\"FIFAD\" TEXT," + // 13: fifad
                "\"XQDZ\" TEXT," + // 14: xqdz
                "\"X\" REAL," + // 15: x
                "\"Y\" REAL," + // 16: y
                "\"GXSJ\" INTEGER," + // 17: gxsj
                "\"WYXX\" TEXT," + // 18: wyxx
                "\"LXDH\" TEXT," + // 19: lxdh
                "\"GLGX\" TEXT," + // 20: glgx
                "\"XQMJ\" REAL," + // 21: xqmj
                "\"OPTUSER\" TEXT," + // 22: optuser
                "\"LAT\" REAL," + // 23: lat
                "\"LNG\" REAL," + // 24: lng
                "\"OPTTIME\" INTEGER," + // 25: opttime
                "\"TYPE\" TEXT," + // 26: type
                "\"LYSL\" TEXT," + // 27: lysl
                "\"ZHS\" TEXT," + // 28: zhs
                "\"LDS\" TEXT," + // 29: lds
                "\"BJ\" TEXT," + // 30: bj
                "\"IMG\" TEXT," + // 31: img
                "\"FLAG\" INTEGER NOT NULL );"); // 32: flag
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TSOCIAL_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TSocialInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUid());
 
        String bm = entity.getBm();
        if (bm != null) {
            stmt.bindString(3, bm);
        }
 
        String csbs = entity.getCsbs();
        if (csbs != null) {
            stmt.bindString(4, csbs);
        }
 
        String qxbs = entity.getQxbs();
        if (qxbs != null) {
            stmt.bindString(5, qxbs);
        }
 
        String xzbs = entity.getXzbs();
        if (xzbs != null) {
            stmt.bindString(6, xzbs);
        }
 
        String gsjd = entity.getGsjd();
        if (gsjd != null) {
            stmt.bindString(7, gsjd);
        }
 
        String xqid = entity.getXqid();
        if (xqid != null) {
            stmt.bindString(8, xqid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(9, name);
        }
 
        String firstad = entity.getFirstad();
        if (firstad != null) {
            stmt.bindString(10, firstad);
        }
 
        String secondad = entity.getSecondad();
        if (secondad != null) {
            stmt.bindString(11, secondad);
        }
 
        String thirdad = entity.getThirdad();
        if (thirdad != null) {
            stmt.bindString(12, thirdad);
        }
 
        String forthad = entity.getForthad();
        if (forthad != null) {
            stmt.bindString(13, forthad);
        }
 
        String fifad = entity.getFifad();
        if (fifad != null) {
            stmt.bindString(14, fifad);
        }
 
        String xqdz = entity.getXqdz();
        if (xqdz != null) {
            stmt.bindString(15, xqdz);
        }
 
        Double x = entity.getX();
        if (x != null) {
            stmt.bindDouble(16, x);
        }
 
        Double y = entity.getY();
        if (y != null) {
            stmt.bindDouble(17, y);
        }
 
        java.util.Date gxsj = entity.getGxsj();
        if (gxsj != null) {
            stmt.bindLong(18, gxsj.getTime());
        }
 
        String wyxx = entity.getWyxx();
        if (wyxx != null) {
            stmt.bindString(19, wyxx);
        }
 
        String lxdh = entity.getLxdh();
        if (lxdh != null) {
            stmt.bindString(20, lxdh);
        }
 
        String glgx = entity.getGlgx();
        if (glgx != null) {
            stmt.bindString(21, glgx);
        }
 
        Double xqmj = entity.getXqmj();
        if (xqmj != null) {
            stmt.bindDouble(22, xqmj);
        }
 
        String optuser = entity.getOptuser();
        if (optuser != null) {
            stmt.bindString(23, optuser);
        }
 
        Double lat = entity.getLat();
        if (lat != null) {
            stmt.bindDouble(24, lat);
        }
 
        Double lng = entity.getLng();
        if (lng != null) {
            stmt.bindDouble(25, lng);
        }
 
        java.util.Date opttime = entity.getOpttime();
        if (opttime != null) {
            stmt.bindLong(26, opttime.getTime());
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(27, type);
        }
 
        String lysl = entity.getLysl();
        if (lysl != null) {
            stmt.bindString(28, lysl);
        }
 
        String zhs = entity.getZhs();
        if (zhs != null) {
            stmt.bindString(29, zhs);
        }
 
        String lds = entity.getLds();
        if (lds != null) {
            stmt.bindString(30, lds);
        }
 
        String bj = entity.getBj();
        if (bj != null) {
            stmt.bindString(31, bj);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(32, img);
        }
        stmt.bindLong(33, entity.getFlag());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TSocialInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUid());
 
        String bm = entity.getBm();
        if (bm != null) {
            stmt.bindString(3, bm);
        }
 
        String csbs = entity.getCsbs();
        if (csbs != null) {
            stmt.bindString(4, csbs);
        }
 
        String qxbs = entity.getQxbs();
        if (qxbs != null) {
            stmt.bindString(5, qxbs);
        }
 
        String xzbs = entity.getXzbs();
        if (xzbs != null) {
            stmt.bindString(6, xzbs);
        }
 
        String gsjd = entity.getGsjd();
        if (gsjd != null) {
            stmt.bindString(7, gsjd);
        }
 
        String xqid = entity.getXqid();
        if (xqid != null) {
            stmt.bindString(8, xqid);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(9, name);
        }
 
        String firstad = entity.getFirstad();
        if (firstad != null) {
            stmt.bindString(10, firstad);
        }
 
        String secondad = entity.getSecondad();
        if (secondad != null) {
            stmt.bindString(11, secondad);
        }
 
        String thirdad = entity.getThirdad();
        if (thirdad != null) {
            stmt.bindString(12, thirdad);
        }
 
        String forthad = entity.getForthad();
        if (forthad != null) {
            stmt.bindString(13, forthad);
        }
 
        String fifad = entity.getFifad();
        if (fifad != null) {
            stmt.bindString(14, fifad);
        }
 
        String xqdz = entity.getXqdz();
        if (xqdz != null) {
            stmt.bindString(15, xqdz);
        }
 
        Double x = entity.getX();
        if (x != null) {
            stmt.bindDouble(16, x);
        }
 
        Double y = entity.getY();
        if (y != null) {
            stmt.bindDouble(17, y);
        }
 
        java.util.Date gxsj = entity.getGxsj();
        if (gxsj != null) {
            stmt.bindLong(18, gxsj.getTime());
        }
 
        String wyxx = entity.getWyxx();
        if (wyxx != null) {
            stmt.bindString(19, wyxx);
        }
 
        String lxdh = entity.getLxdh();
        if (lxdh != null) {
            stmt.bindString(20, lxdh);
        }
 
        String glgx = entity.getGlgx();
        if (glgx != null) {
            stmt.bindString(21, glgx);
        }
 
        Double xqmj = entity.getXqmj();
        if (xqmj != null) {
            stmt.bindDouble(22, xqmj);
        }
 
        String optuser = entity.getOptuser();
        if (optuser != null) {
            stmt.bindString(23, optuser);
        }
 
        Double lat = entity.getLat();
        if (lat != null) {
            stmt.bindDouble(24, lat);
        }
 
        Double lng = entity.getLng();
        if (lng != null) {
            stmt.bindDouble(25, lng);
        }
 
        java.util.Date opttime = entity.getOpttime();
        if (opttime != null) {
            stmt.bindLong(26, opttime.getTime());
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(27, type);
        }
 
        String lysl = entity.getLysl();
        if (lysl != null) {
            stmt.bindString(28, lysl);
        }
 
        String zhs = entity.getZhs();
        if (zhs != null) {
            stmt.bindString(29, zhs);
        }
 
        String lds = entity.getLds();
        if (lds != null) {
            stmt.bindString(30, lds);
        }
 
        String bj = entity.getBj();
        if (bj != null) {
            stmt.bindString(31, bj);
        }
 
        String img = entity.getImg();
        if (img != null) {
            stmt.bindString(32, img);
        }
        stmt.bindLong(33, entity.getFlag());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TSocialInfo readEntity(Cursor cursor, int offset) {
        TSocialInfo entity = new TSocialInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // uid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bm
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // csbs
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // qxbs
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // xzbs
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // gsjd
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // xqid
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // name
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // firstad
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // secondad
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // thirdad
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // forthad
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // fifad
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // xqdz
            cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15), // x
            cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16), // y
            cursor.isNull(offset + 17) ? null : new java.util.Date(cursor.getLong(offset + 17)), // gxsj
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // wyxx
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // lxdh
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // glgx
            cursor.isNull(offset + 21) ? null : cursor.getDouble(offset + 21), // xqmj
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // optuser
            cursor.isNull(offset + 23) ? null : cursor.getDouble(offset + 23), // lat
            cursor.isNull(offset + 24) ? null : cursor.getDouble(offset + 24), // lng
            cursor.isNull(offset + 25) ? null : new java.util.Date(cursor.getLong(offset + 25)), // opttime
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // type
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // lysl
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // zhs
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // lds
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // bj
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // img
            cursor.getInt(offset + 32) // flag
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TSocialInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUid(cursor.getInt(offset + 1));
        entity.setBm(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCsbs(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setQxbs(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setXzbs(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setGsjd(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setXqid(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setFirstad(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSecondad(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setThirdad(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setForthad(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setFifad(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setXqdz(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setX(cursor.isNull(offset + 15) ? null : cursor.getDouble(offset + 15));
        entity.setY(cursor.isNull(offset + 16) ? null : cursor.getDouble(offset + 16));
        entity.setGxsj(cursor.isNull(offset + 17) ? null : new java.util.Date(cursor.getLong(offset + 17)));
        entity.setWyxx(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setLxdh(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setGlgx(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setXqmj(cursor.isNull(offset + 21) ? null : cursor.getDouble(offset + 21));
        entity.setOptuser(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setLat(cursor.isNull(offset + 23) ? null : cursor.getDouble(offset + 23));
        entity.setLng(cursor.isNull(offset + 24) ? null : cursor.getDouble(offset + 24));
        entity.setOpttime(cursor.isNull(offset + 25) ? null : new java.util.Date(cursor.getLong(offset + 25)));
        entity.setType(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setLysl(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setZhs(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setLds(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setBj(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setImg(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setFlag(cursor.getInt(offset + 32));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TSocialInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TSocialInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TSocialInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
